/**
 * Copyright (c) 2019 Aspicat - Florian Roth
 */

#ifndef SHADERIDE_CORE_APPLICATIONDEFAULTS_HPP
#define SHADERIDE_CORE_APPLICATIONDEFAULTS_HPP

#define SHADERIDE_APPLICATION_NAME  "Shader IDE"
#define SHADERIDE_PROJECT_EXTENSION "*.shaderide"
#define SHADERIDE_STATUSBAR_TIMEOUT 10000 // 10 Seconds

#endif // SHADERIDE_CORE_APPLICATIONDEFAULTS_HPP
